# Just a dirty hack to get the jms serializer bundle correctly working
# https://github.com/schmittjoh/JMSSerializerBundle/pull/270#issuecomment-21171800
services:
    jms_serializer.cache_naming_strategy: "@sulu_core.serialize_caching_strategy"
