sulu_admin:
    email: "%env(SULU_ADMIN_EMAIL)%"
    forms:
        directories:
            - "%kernel.project_dir%/config/forms"
    datagrids:
        directories:
            - "%kernel.project_dir%/config/datagrids"
