sudo: false

language: php

cache:
  directories:
    - "$HOME/.composer/cache/files"

matrix:
  include:
    - php: 5.5
      env:
        - COMPOSER_FLAGS="--prefer-dist --no-interaction"
    - php: 7.1
      env:
        - COMPOSER_FLAGS="--prefer-dist --no-interaction"

before_install:
  - composer self-update
  - phpenv config-add tests/travis.php.ini

install:
  # Install dependencies
  - travis_retry composer update $COMPOSER_FLAGS
  - composer info -i
  # Create database for build test
  - bin/adminconsole doctrine:database:create
  # Create database for unit test
  - bin/adminconsole doctrine:database:create --env=test

script:
  # Test if installation works
  - bin/adminconsole sulu:build dev --no-interaction
  # Lint Twig files
  - bin/adminconsole lint:twig app/Resources/views
  # Lint Yaml files
  - bin/adminconsole lint:yaml app/config
  # Test if PHPUnit installation works
  - bin/simple-phpunit
