sudo: false

language: php

cache:
  directories:
    - "$HOME/.composer/cache/files"

env:
  global:
    - APP_ENV="test"
    - APP_SECRET=a448d1dfcaa563fce56c2fd9981f662b
    - MAILER_URL=null://localhost
    - SULU_ADMIN_EMAIL=
    - JACKRABBIT_VERSION=2.12.0
    - PHPCR_TRANSPORT=doctrinedbal
    - DATABASE_URL=mysql://root:@127.0.0.1/sulu_test
    - DATABASE_VERSION=5.6
    - DATABASE_CHARSET=utf8mb4
    - DATABASE_COLLATE=utf8mb4_unicode_ci

matrix:
  include:
    - php: 7.1
      env:
        - COMPOSER_FLAGS="--no-interaction"

before_install:
  - composer self-update
  - phpenv config-add tests/travis.php.ini

install:
  # Install dependencies
  - travis_retry composer update $COMPOSER_FLAGS
  - composer info -i
  # Install node
  - nvm install 8
  - npm install -g npm
  - npm install
  # Create database for build test
  - bin/adminconsole doctrine:database:create

script:
  # Test if installation works
  - bin/adminconsole sulu:build dev --no-interaction
  # Test if PHPUnit installation works
  - bin/simple-phpunit
  # Lint Twig files
  - bin/adminconsole lint:twig templates
  # Lint Yaml files
  - bin/adminconsole lint:yaml config
  # Test webpack build
  - npm run build
