imports:
    - { resource: ../config.yml }

# SuluAdmin Configuration
sulu_admin:
    name: "%sulu_admin.name%"
    email: "%sulu_admin.email%"

framework:
    session:
        cookie_path: /admin
    fragments:
        path: /admin/_fragments

