_wdt:
    defaults:
        _requestAnalyzer: false
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    defaults:
        _requestAnalyzer: false
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_main:
    resource: routing.yml

_portal_errors:
    resource: "@SuluWebsiteBundle/Resources/config/routing_error.yml"
    type: portal
