framework:
    router:
        resource: "%kernel.root_dir%/config/%sulu.context%/routing_stage.yml"

monolog:
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: info
