version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
        environment:
          - APP_ENV=test
          - APP_SECRET=a448d1dfcaa563fce56c2fd9981f662b
          - MAILER_URL=null://localhost
          - SULU_ADMIN_EMAIL=
          - JACKRABBIT_VERSION=2.12.0
          - PHPCR_TRANSPORT=doctrinedbal
          - DATABASE_URL=mysql://root:@127.0.0.1/circle_test
          - DATABASE_VERSION=5.6
          - DATABASE_CHARSET=utf8mb4
          - DATABASE_COLLATE=utf8mb4_unicode_ci
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_USER=root
          - MYSQL_PASSWORD=
          - MYSQL_ALLOW_EMPTY_PASSWORD=true
          - MYSQL_DATABASE=circle_test
    steps:
      - checkout
      - run: 
          name: Install OS dependencies (mysql, gd)
          command: |
            sudo apt-get install -y libpng-dev
            sudo docker-php-ext-install pdo_mysql gd
          parallel: true
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: php -d memory_limit=-1 /usr/local/bin/composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
            - ~/.composer/cache
      # Node
      - run: npm install
      - run: npm run build
