sylius_product:
    resources:
        product:
            classes:
                model: Sulu\Bundle\ProductBundle\Entity\Product

sylius_attribute:
    resources:
        product:
            attribute:
                classes:
                    model: Sulu\Bundle\ProductBundle\Entity\Attribute
