sylius_product:
    resources:
        product:
            classes:
                model: Sulu\Bundle\ProductBundle\Entity\Product
        product_option:
            classes:
                model: Sulu\Bundle\ProductBundle\Entity\Option


sylius_attribute:
    resources:
        product:
            attribute:
                classes:
                    model: Sulu\Bundle\ProductBundle\Entity\Attribute
